### ISSUE TITLE
Site not opening

### ISSUE THREAD

**Issue by aiamanme** [iyansr/iyansr.id-reborn#28]
I recently tried to checkout the site. but i think its not working.
![image](https://github.com/iyansr/iyansr.id-reborn/assets/123186924/e5973b13-d2a4-4254-9303-a3360e53f969)

**Comment by iyansr** [comment]
Hi, thanks for reporting
I recently visit the website and it working well ![image](https://github.com/iyansr/iyansr.id-reborn/assets/42711013/5e5362be-c5a5-4772-a090-27e51e9d80fe)

**Comment by aiamanme** [comment]
I recently visited your website, and now it's functioning well.
